config/routes.rb
TabScribe::Application.routes.draw do
  resources :s_tabs

  root :to => 'static_pages#home'

  match '/help', to: "static_pages#help", via: 'get'

  match '/about', to: "static_pages#about", via: 'get'

  mount Resque::Server, at: "/resque"

end

app/models/s_tab.rb
class STab < ActiveRecord::Base
  attr_accessible :contents, :name, :original_url

  validates(:name, presence: true)
  validates(:contents, presence: true)
  validates(:original_url, presence: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/s_tabs_controller.rb
class STabsController < ApplicationController

  require 'open-uri'

  def new
    @stab = STab.new
  end

  def show
    @stab = STab.find(params[:id])
  end

  def create
    hashy = params[:s_tab]
    hashy[:name] = "Scribed Tab"
    hashy[:contents] = "hello"
    @stab = STab.new(hashy)
    if @stab.save
      Resque.enqueue(TabTranslator, @stab.id)      
      redirect_to @stab
    else
      render 'new'
    end
  end

private

  # generate a params hash for a newly created  s_tab
=begin
  def stab_params

    base_url = "http://tabs.ultimate-guitar.com"
    user_agent = "Mozilla/4.0 (Compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"
    hash = params[:s_tab]
    hash[:name] = "Thingy"
    doc =  Nokogiri::HTML(open(hash[:original_url]))
    print_url = doc.css('a.pr_b').first["href"]
    doc2 = Nokogiri::HTML(open(base_url + print_url, "User-Agent" => user_agent, "Referer" => hash[:original_url]))
    hash[:contents] = doc2.css('pre').first.text
    hash
  end
=end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @stab = STab.new
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/s_tabs_helper.rb
module STabsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <small>
    &copy Mark Willson 2014
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div class="logo">
      <%= link_to image_tag("transparent-logo2.png", size: "450x180", alt: "TabScribe"), '/' %>
      </div>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Help", help_path %></li>
        </ul>
      </nav>
    </div>    
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stabform.html.erb
<div class="row">
<div class="span6 offset3">
<%= form_for(@stab) do |f| %>

  <%= f.label :original_url, "Ultimate Guitar Tab URL" %>
  <%= f.text_field :original_url %>

  <%= f.submit "Scribe It!", class: "btn btn-large" %>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TabScribe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container bod">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/s_tabs/new.html.erb
<h1>STabs#new</h1>
<p><%= render 'layouts/stabform' %></p>

app/views/s_tabs/show.html.erb
<h1>
<%= @stab.name %>
</h1>
<br/>
<pre class="container"><%= @stab.contents %></pre>

app/views/static_pages/about.html.erb
<h1>About TabScribe</h1>

app/views/static_pages/help.html.erb
<h1>FAQ</h1>
<br/>
<h5>Q: When will this site be up?</h5>
<p>Hopefully by the end of the weekend</p>

app/views/static_pages/home.html.erb
<div>
<h1>Under Construction</h1>
<h3>Full Site Coming Soon</h3>
<%= render 'layouts/stabform' %>
</div>